---
- hosts: all
  tasks:
    - yum: 
        name: vim
        state: latest
    - yum: 
        name: httpd
        state: latest
    - yum: 
        name: firewalld
        state: latest
    - service: 
        name: firewalld
        state: started
        enabled: true
    - service:
        name: httpd
        state: started
        enabled: true
    - firewalld: 
        service: http
        immediately : true
        permanent: true
        state: enabled
    - service:
        name: httpd
        state: restarted
        enabled: true
