---
- hosts: localhost
  remote_user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - yum: 
        name: vim
        state: latest
    - yum: 
        name: httpd
        state: latest
    - service:
        name: httpd
        state: started
        enabled: true
    - service:
        name: httpd
        state: restarted
        enabled: true
